#!/usr/bin/python3

#import subprocess
import sys
#output = subprocess.run(["git", "log"], stdout=subprocess.PIPE)

#log = output.stdout.decode('utf-8')

#words = log.split('\n')

#words = a.split(' ')


words = sys.stdin
#print(words)
words2 = []
#for line in range(len(words)):
    #words2.append(words[i].split(' '))
#print(words2)

for line in sys.stdin:
    words2.append(line.split(' '))
    
#print(words2)

class timezones:
    def __init__(self, name):
        self.name = name
        self.count = 1
        return

    def found(self):
        self.count = self.count + 1
        return

zones = []

def zonename(i):
        return i.name
    
for i in range(len(words2)):
    if words2[i][0] == "Date:":
        zones.append(words2[i][8])

added = False

found = []
#look for any timezones that have been found, increase count if existing
for i in range(len(zones)):
    if len(found) == 0:
        a = timezones(zones[i])
        found.append(a)
    else:
        for j in range(len(found)):
            #print('b')
            if zones[i] == found[j].name:
                #print('c')
                found[j].count = found[j].count + 1
                added = True
                break
        if added == False:
            #print('d')
            a = timezones(zones[i])
            found.append(a)
            added = True
    added = False

#order the timezones in found
found.sort(reverse = True, key=zonename)

#to sort the positives: remove the +, sort it, then add the + back

positives = []
negatives = []

for i in found:
    #this removes the +
    if i.name[0] == '+':
        i.name.replace('+', '', 1)
        positives.append(i)
    else:
        negatives.append(i)

#sort the positives
positives.sort(reverse=False, key=zonename)

#now add the + back
for i in positives:
    if i.name[0] == '':
        i.name.replace('', '+', 1)

found = negatives + positives

for i in found:
    #print(i)
    print(i.name.replace('\n', '') + ' ' + str(i.count))
#count amt of zones


